### ISSUE TITLE
Ao cadastrar autores, não está seguindo o ID. 

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#106]
Após a inserção o número do ID fica 0 para todos os novos registros

(relato usuário final)

**Comment by carlosed999** [comment]
![image](https://github.com/user-attachments/assets/3db20bb1-1b55-4940-8449-59b3436b6072)

**Comment by Ronneesley** [comment]
Conforme a imagem anexada por @carlosed999

**Comment by Ronneesley** [comment]
Feito
