### ISSUE TITLE
Criar um protótipo da tela de cadastro de avaliadores

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#11]
Sugestões de campos: nome, senha, curso, formação (bacharel, especialista, mestre, doutor),

Exemplos de área: Sistema de Informação, Agronomia, etc.

**Comment by Carl0sPaiva** [comment]
Boa noite professor, venho por meio deste, solicitar informações sobre o projeto, esse seria um modelo ideal de protótipo para a tela de login dos avaliados?  
[PROJETO II.pdf](https://github.com/Ronneesley/sistema_submissao_resumos_simples/files/14466776/PROJETO.II.pdf)

**Comment by Carl0sPaiva** [comment]
[Uploading prototipo.pdf…]()

**Comment by Carl0sPaiva** [comment]
[prototipo.pdf](https://github.com/Ronneesley/sistema_submissao_resumos_simples/files/14658009/prototipo.pdf)

**Comment by Ronneesley** [comment]
Feito
