### ISSUE TITLE
Documentar o teste do CRUD de autores

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#117]

**Comment by jailsonsantana** [comment]
Feito

**Comment by Ronneesley** [comment]
No item (Selecionar), tópico 3: "Preencher o cadastro com dados fictícios"
Você deve falar quais são os dados a serem preenchidos, para cada campo. 
De forma que o teste seja repetido exatamente toda vez com os mesmos valores.

**Comment by Ronneesley** [comment]
Feita
