### ISSUE TITLE
Criar o protótipo do painel inicial do avaliador

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#15]
Mostrar para o avaliador o percentual de conclusão das suas avaliações, exemplo

Evento A: 7/20

Evento B: 8/15

**Comment by jailsonsantana** [comment]
Prototipagem disponível em:
https://www.figma.com/file/ErM4c9DerJvTcxIePT3MUm/PAINEL-INICIAL---AVALIADOR?type=design&mode=design&t=RsLhopSXayE3Zpb5-1

**Comment by Ronneesley** [comment]
Feito
