### ISSUE TITLE
Criar o diagrama de componentes do CRUD de resumos

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#87]

**Comment by carolxn10** [comment]
Professor, como eu vou fazer esse diagrama sendo que eu fui olhar a listagem do resumo e não tinha nada lá a não ser o css. Eu fiz o diagrama mais não sei se está certo, vou mandar por aqui e o senhor olha e me fala :)
![IMG_0581](https://github.com/user-attachments/assets/dce28b18-080b-4799-b701-b5052a4c9afa)
