### ISSUE TITLE
Criar o protótipo da listagem de autores

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/sistema_submissao_resumos_simples#9]
Ela deverá incluir uma busca. 
Pense sobre os filtros que serão úteis nesta listagem. 
Além disso, pense também em uma paginação.

**Comment by Carl0sPaiva** [comment]
[LISTA (2).pdf](https://github.com/Ronneesley/sistema_submissao_resumos_simples/files/14657999/LISTA.2.pdf)

**Comment by Ronneesley** [comment]
Feito
